
package Domain;
import java.awt.Container;
import javax.swing.*;
/**
 *
 * @author Luis Angel Mendez
 */
public class Panel_protocolos extends javax.swing.JFrame {

    /**
     * Creates new form Panel_protcolosnew
     */
    public Panel_protocolos() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_ccd = new javax.swing.JButton();
        btn_can = new javax.swing.JButton();
        btn_vpw = new javax.swing.JButton();
        btn_iso = new javax.swing.JButton();
        btn_pwm = new javax.swing.JButton();
        btn_sci = new javax.swing.JButton();
        btn_todos1 = new javax.swing.JButton();
        btn_Regresar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        Panel_Inicial_PROTOCOLOS = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panel_VPW = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel_ISO = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_PWM = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel_SCI = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panel_TODOS = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel_CCD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel_CAN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btnSI_protocolos = new javax.swing.JButton();
        btnNO_protocolos = new javax.swing.JButton();
        PanelNO_CAN = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnSI_protocolos1 = new javax.swing.JButton();
        btnNO_protocolos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ccd.setText("CCD");
        btn_ccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ccdActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ccd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 145, -1));

        btn_can.setText("CAN");
        btn_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_canActionPerformed(evt);
            }
        });
        jPanel2.add(btn_can, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 145, -1));

        btn_vpw.setText("J1850_VPW");
        btn_vpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vpwActionPerformed(evt);
            }
        });
        jPanel2.add(btn_vpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 145, -1));

        btn_iso.setText("ISO");
        btn_iso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_isoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_iso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 145, -1));

        btn_pwm.setText("J1850_PWM");
        btn_pwm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pwmActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pwm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 145, -1));

        btn_sci.setText("SCI");
        btn_sci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sciActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sci, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 145, -1));

        btn_todos1.setText("Regresar ");
        btn_todos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todos1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_todos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 90, 20));

        btn_Regresar.setText("TODOS");
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 145, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Domain/IMAGES/black_protcols.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 520));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        Panel_Inicial_PROTOCOLOS.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Inicial_PROTOCOLOS.setName("Panel_inicial_PROTOCOLOS"); // NOI18N

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("SELECCIONA EL PROTOCOLO QUE DESEAS DIAGNOSTICAR");

        javax.swing.GroupLayout Panel_Inicial_PROTOCOLOSLayout = new javax.swing.GroupLayout(Panel_Inicial_PROTOCOLOS);
        Panel_Inicial_PROTOCOLOS.setLayout(Panel_Inicial_PROTOCOLOSLayout);
        Panel_Inicial_PROTOCOLOSLayout.setHorizontalGroup(
            Panel_Inicial_PROTOCOLOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Inicial_PROTOCOLOSLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        Panel_Inicial_PROTOCOLOSLayout.setVerticalGroup(
            Panel_Inicial_PROTOCOLOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Inicial_PROTOCOLOSLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(Panel_Inicial_PROTOCOLOS, "card9");

        panel_VPW.setName("panel_VPW"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INFORMACION PROTOCOLO VPW");

        javax.swing.GroupLayout panel_VPWLayout = new javax.swing.GroupLayout(panel_VPW);
        panel_VPW.setLayout(panel_VPWLayout);
        panel_VPWLayout.setHorizontalGroup(
            panel_VPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_VPWLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(523, Short.MAX_VALUE))
        );
        panel_VPWLayout.setVerticalGroup(
            panel_VPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_VPWLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(panel_VPW, "card4");

        panel_ISO.setName("panel_ISO"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INFORMACION PROTOCOLO ISO");

        javax.swing.GroupLayout panel_ISOLayout = new javax.swing.GroupLayout(panel_ISO);
        panel_ISO.setLayout(panel_ISOLayout);
        panel_ISOLayout.setHorizontalGroup(
            panel_ISOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ISOLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        panel_ISOLayout.setVerticalGroup(
            panel_ISOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ISOLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(panel_ISO, "card5");

        panel_PWM.setName("panel_PWM"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INFORMACION PROTOCOLO PWM");

        javax.swing.GroupLayout panel_PWMLayout = new javax.swing.GroupLayout(panel_PWM);
        panel_PWM.setLayout(panel_PWMLayout);
        panel_PWMLayout.setHorizontalGroup(
            panel_PWMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PWMLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        panel_PWMLayout.setVerticalGroup(
            panel_PWMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PWMLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(panel_PWM, "card6");

        panel_SCI.setName("panel_SCI"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INFORMACION PROTOCOLO SCI");

        javax.swing.GroupLayout panel_SCILayout = new javax.swing.GroupLayout(panel_SCI);
        panel_SCI.setLayout(panel_SCILayout);
        panel_SCILayout.setHorizontalGroup(
            panel_SCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SCILayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        panel_SCILayout.setVerticalGroup(
            panel_SCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SCILayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(panel_SCI, "card7");

        panel_TODOS.setName("panel_TODOS"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INFORMACION PROTOCOLO TODOS");

        javax.swing.GroupLayout panel_TODOSLayout = new javax.swing.GroupLayout(panel_TODOS);
        panel_TODOS.setLayout(panel_TODOSLayout);
        panel_TODOSLayout.setHorizontalGroup(
            panel_TODOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TODOSLayout.createSequentialGroup()
                .addContainerGap(492, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        panel_TODOSLayout.setVerticalGroup(
            panel_TODOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TODOSLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(panel_TODOS, "card8");

        panel_CCD.setName("panel_CCD"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMACION PROTOCOLO CCD");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Domain/IMAGES/PCB_CJ4R.png"))); // NOI18N

        javax.swing.GroupLayout panel_CCDLayout = new javax.swing.GroupLayout(panel_CCD);
        panel_CCD.setLayout(panel_CCDLayout);
        panel_CCDLayout.setHorizontalGroup(
            panel_CCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CCDLayout.createSequentialGroup()
                .addGroup(panel_CCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_CCDLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8))
                    .addGroup(panel_CCDLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        panel_CCDLayout.setVerticalGroup(
            panel_CCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CCDLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(panel_CCD, "card2");

        panel_CAN.setName("panel_CAN"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFORMACION PROTOCOLO CAN");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Domain/IMAGES/PCB_CJ4R-ADG333.png"))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("REMPLAZA:\nNO.PARTE:11-0056-0000\nREFERENCIA PCB: U7\nDESCRIPCION: ADG333ABR SWITCH ANALOGO ");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Se soluciono cambiando este componente?");

        btnSI_protocolos.setBackground(new java.awt.Color(0, 153, 0));
        btnSI_protocolos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSI_protocolos.setText("SI");
        btnSI_protocolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSI_protocolosActionPerformed(evt);
            }
        });

        btnNO_protocolos.setBackground(new java.awt.Color(204, 0, 0));
        btnNO_protocolos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnNO_protocolos.setText("NO");
        btnNO_protocolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNO_protocolosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_CANLayout = new javax.swing.GroupLayout(panel_CAN);
        panel_CAN.setLayout(panel_CANLayout);
        panel_CANLayout.setHorizontalGroup(
            panel_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CANLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGroup(panel_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_CANLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnSI_protocolos)
                        .addGap(39, 39, 39)
                        .addComponent(btnNO_protocolos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CANLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panel_CANLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panel_CANLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_CANLayout.setVerticalGroup(
            panel_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CANLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_CANLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_CANLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSI_protocolos)
                            .addComponent(btnNO_protocolos))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(panel_CAN, "card3");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Domain/IMAGES/PCB_CJ4R-U3.png"))); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("REMPLAZA:\nNO.PARTE:11-0056-0000\nREFERENCIA PCB: U3\nDESCRIPCION: MCP2551-I/SN CAN TRANSCEIVER ANALOGO ");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("INFORMACION PROTOCOLO CAN");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Se soluciono cambiando este componente?");

        btnSI_protocolos1.setBackground(new java.awt.Color(0, 153, 0));
        btnSI_protocolos1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSI_protocolos1.setText("SI");
        btnSI_protocolos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSI_protocolos1ActionPerformed(evt);
            }
        });

        btnNO_protocolos1.setBackground(new java.awt.Color(204, 0, 0));
        btnNO_protocolos1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnNO_protocolos1.setText("NO");
        btnNO_protocolos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNO_protocolos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNO_CANLayout = new javax.swing.GroupLayout(PanelNO_CAN);
        PanelNO_CAN.setLayout(PanelNO_CANLayout);
        PanelNO_CANLayout.setHorizontalGroup(
            PanelNO_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNO_CANLayout.createSequentialGroup()
                .addGroup(PanelNO_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNO_CANLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelNO_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelNO_CANLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(PanelNO_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelNO_CANLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(btnSI_protocolos1)
                                        .addGap(44, 44, 44)
                                        .addComponent(btnNO_protocolos1))))
                            .addGroup(PanelNO_CANLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))))
                    .addGroup(PanelNO_CANLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        PanelNO_CANLayout.setVerticalGroup(
            PanelNO_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNO_CANLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelNO_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNO_CANLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel15)
                        .addGap(36, 36, 36)
                        .addGroup(PanelNO_CANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNO_protocolos1)
                            .addComponent(btnSI_protocolos1)))
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(PanelNO_CAN, "card10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sciActionPerformed
        if(!this.btn_sci.isSelected()){
        this.btn_ccd.setSelected(false);
        this.btn_can.setSelected(false);
        this.btn_vpw.setSelected(false);
        this.btn_iso.setSelected(false);
        this.btn_pwm.setSelected(false);
        this.btn_sci.setSelected(true);
        this.btn_Regresar.setSelected(false);
        //paneles
        Panel_Inicial_PROTOCOLOS.setVisible(false);
        panel_CCD.setVisible(false);
        panel_CAN.setVisible(false);
        panel_VPW.setVisible(false);
        panel_ISO.setVisible(false);
        panel_PWM.setVisible(false);
        panel_SCI.setVisible(true);
        panel_TODOS.setVisible(false);
        }
    }//GEN-LAST:event_btn_sciActionPerformed

    private void btn_ccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ccdActionPerformed
        if(!this.btn_ccd.isSelected()){
        this.btn_ccd.setSelected(true);
        this.btn_can.setSelected(false);
        this.btn_vpw.setSelected(false);
        this.btn_iso.setSelected(false);
        this.btn_pwm.setSelected(false);
        this.btn_sci.setSelected(false);
        this.btn_Regresar.setSelected(false);
        //paneles
        Panel_Inicial_PROTOCOLOS.setVisible(false);
        panel_CCD.setVisible(true);
        panel_CAN.setVisible(false);
        panel_VPW.setVisible(false);
        panel_ISO.setVisible(false);
        panel_PWM.setVisible(false);
        panel_SCI.setVisible(false);
        panel_TODOS.setVisible(false);
        }
    }//GEN-LAST:event_btn_ccdActionPerformed

    private void btn_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_canActionPerformed
        if(!this.btn_can.isSelected()){
        this.btn_ccd.setSelected(false);
        this.btn_can.setSelected(true);
        this.btn_vpw.setSelected(false);
        this.btn_iso.setSelected(false);
        this.btn_pwm.setSelected(false);
        this.btn_sci.setSelected(false);
        this.btn_Regresar.setSelected(false);
        //paneles
        Panel_Inicial_PROTOCOLOS.setVisible(false);
        panel_CCD.setVisible(false);
        panel_CAN.setVisible(true);
        panel_VPW.setVisible(false);
        panel_ISO.setVisible(false);
        panel_PWM.setVisible(false);
        panel_SCI.setVisible(false);
        panel_TODOS.setVisible(false);
    }//GEN-LAST:event_btn_canActionPerformed
    }
    private void btn_vpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vpwActionPerformed
          if(!this.btn_vpw.isSelected()){
          this.btn_ccd.setSelected(false);
          this.btn_can.setSelected(false);
          this.btn_vpw.setSelected(true);
          this.btn_iso.setSelected(false);
          this.btn_pwm.setSelected(false);
          this.btn_sci.setSelected(false);
          this.btn_Regresar.setSelected(false);
          //paneles
          Panel_Inicial_PROTOCOLOS.setVisible(false);
              panel_CCD.setVisible(false);
              panel_CAN.setVisible(false);
              panel_VPW.setVisible(true);
              panel_ISO.setVisible(false);
              panel_PWM.setVisible(false);
              panel_SCI.setVisible(false);
              panel_TODOS.setVisible(false);
    }//GEN-LAST:event_btn_vpwActionPerformed
    }
    private void btn_isoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_isoActionPerformed
        if(!this.btn_iso.isSelected()){
          this.btn_ccd.setSelected(false);
          this.btn_can.setSelected(false);
          this.btn_vpw.setSelected(false);
          this.btn_iso.setSelected(true);
          this.btn_pwm.setSelected(false);
          this.btn_sci.setSelected(false);
          this.btn_Regresar.setSelected(false);
          //paneles
          Panel_Inicial_PROTOCOLOS.setVisible(false);
            panel_CCD.setVisible(false);
            panel_CAN.setVisible(false);
            panel_VPW.setVisible(false);
            panel_ISO.setVisible(true);
            panel_PWM.setVisible(false);
            panel_SCI.setVisible(false);
            panel_TODOS.setVisible(false);
    }//GEN-LAST:event_btn_isoActionPerformed
    }
    private void btn_pwmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pwmActionPerformed
        if(!this.btn_vpw.isSelected()){
          this.btn_ccd.setSelected(false);
          this.btn_can.setSelected(false);
          this.btn_vpw.setSelected(false);
          this.btn_iso.setSelected(false);
          this.btn_pwm.setSelected(true);
          this.btn_sci.setSelected(false);
          this.btn_Regresar.setSelected(false);
          //paneles
          Panel_Inicial_PROTOCOLOS.setVisible(false);
            panel_CCD.setVisible(false);
            panel_CAN.setVisible(false);
            panel_VPW.setVisible(false);
            panel_ISO.setVisible(false);
            panel_PWM.setVisible(true);
            panel_SCI.setVisible(false);
            panel_TODOS.setVisible(false);
    }                                       
    }//GEN-LAST:event_btn_pwmActionPerformed

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        if(!this.btn_Regresar.isSelected()){
          this.btn_ccd.setSelected(false);
          this.btn_can.setSelected(false);
          this.btn_vpw.setSelected(false);
          this.btn_iso.setSelected(false);
          this.btn_pwm.setSelected(false);
          this.btn_sci.setSelected(false);
          this.btn_Regresar.setSelected(true);
          //paneles
          Panel_Inicial_PROTOCOLOS.setVisible(false);
            panel_CCD.setVisible(false);
            panel_CAN.setVisible(false);
            panel_VPW.setVisible(false);
            panel_ISO.setVisible(false);
            panel_PWM.setVisible(false);
            panel_SCI.setVisible(false);
            panel_TODOS.setVisible(true);
    }                                      
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void btn_todos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todos1ActionPerformed
        panel_main panel_main = new panel_main();
        panel_main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_todos1ActionPerformed

    private void btnSI_protocolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSI_protocolosActionPerformed
      byte opcion = 0;
   do{
      opcion=Byte.parseByte(JOptionPane.showInputDialog(
      "***SELECCIONA QUE DESEAS HACER***\n"
    + "1. Volver al menu principal\n"
    + "2. Volver al Menu Protocolos\n"
    + "3. Documentar Mi Falla\n"
    + "4. Salir del Programa\n"));
      switch(opcion){
         case 1:
             panel_main panel_main = new panel_main();
             panel_main.setVisible(true);
             dispose();
            break;
         case 2:
             Panel_protocolos panelprotocolos = new Panel_protocolos();
             panelprotocolos.setVisible(true);
             dispose();
            break;
         case 3:
            JOptionPane.showMessageDialog(null, "Docmumentacion de falla esta en trabajo por el momento");
            break;
         case 4:
             System.exit(0);
         default:
            JOptionPane.showMessageDialog(null, "Opcion Invalida");
            break;
            
      }
   }while(opcion!=opcion);   
    }//GEN-LAST:event_btnSI_protocolosActionPerformed

    private void btnSI_protocolos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSI_protocolos1ActionPerformed
       byte opcion = 0;
   do{
      opcion=Byte.parseByte(JOptionPane.showInputDialog(
      "***SELECCIONA QUE DESEAS HACER***\n"
    + "1. Volver al menu principal\n"
    + "2. Volver al Menu Protocolos\n"
    + "3. Documentar Mi Falla\n"
    + "4. Salir del Programa\n"));
      switch(opcion){
         case 1:
             panel_main panel_main = new panel_main();
             panel_main.setVisible(true);
             dispose();
            break;
         case 2:
             Panel_protocolos panelprotocolos = new Panel_protocolos();
             panelprotocolos.setVisible(true);
             dispose();
            break;
         case 3:
            JOptionPane.showMessageDialog(null, "Docmumentacion de falla esta en trabajo por el momento");
            break;
         case 4:
             System.exit(0);
         default:
            JOptionPane.showMessageDialog(null, "Opcion Invalida");
            break;
            
      }
   }while(opcion!=opcion);   
            
    }//GEN-LAST:event_btnSI_protocolos1ActionPerformed

    private void btnNO_protocolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNO_protocolosActionPerformed
        if(!this.btnNO_protocolos.isSelected()){
            panel_CAN.setVisible(false);
        PanelNO_CAN.setVisible(true);
        }
    }//GEN-LAST:event_btnNO_protocolosActionPerformed

    private void btnNO_protocolos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNO_protocolos1ActionPerformed
       JOptionPane.showMessageDialog(null, "!LO SENTIMOS SE TERMINARON LAS OPCIONES¡ \n"
    + "Contacta un Tecnico Especialista ");
       System.exit(0);
    }//GEN-LAST:event_btnNO_protocolos1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_protocolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_protocolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_protocolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_protocolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_protocolos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNO_CAN;
    private javax.swing.JPanel Panel_Inicial_PROTOCOLOS;
    private javax.swing.JButton btnNO_protocolos;
    private javax.swing.JButton btnNO_protocolos1;
    private javax.swing.JButton btnSI_protocolos;
    private javax.swing.JButton btnSI_protocolos1;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btn_can;
    private javax.swing.JButton btn_ccd;
    private javax.swing.JButton btn_iso;
    private javax.swing.JButton btn_pwm;
    private javax.swing.JButton btn_sci;
    private javax.swing.JButton btn_todos1;
    private javax.swing.JButton btn_vpw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel panel_CAN;
    private javax.swing.JPanel panel_CCD;
    private javax.swing.JPanel panel_ISO;
    private javax.swing.JPanel panel_PWM;
    private javax.swing.JPanel panel_SCI;
    private javax.swing.JPanel panel_TODOS;
    private javax.swing.JPanel panel_VPW;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
